
const rolePresets = [
  { value: "ai_engineer", label: "AI Engineer" },
  { value: "machine_learning_engineer", label: "Machine Learning Engineer" },
  { value: "data_scientist", label: "Data Scientist" },
  { value: "data_engineer", label: "Data Engineer" },
  { value: "software_developer", label: "Software Developer" },
  { value: "backend_developer", label: "Backend Developer" },
  { value: "frontend_developer", label: "Frontend Developer" },
  { value: "full_stack_developer", label: "Full Stack Developer" },
  { value: "devops_engineer", label: "DevOps Engineer" },
  { value: "cloud_architect", label: "Cloud Architect" },
  { value: "cyber_security_specialist", label: "Cyber Security Specialist" },
  { value: "ui_ux_designer", label: "UI/UX Designer" },
  { value: "product_manager", label: "Product Manager" },
  { value: "project_manager", label: "Project Manager" },
  { value: "qa_engineer", label: "QA Engineer" },
  { value: "scrum_master", label: "Scrum Master" },
  { value: "business_analyst", label: "Business Analyst" },
  { value: "customer_success_manager", label: "Customer Success Manager" },
  { value: "technical_support_specialist", label: "Technical Support Specialist" },
  { value: "sales_engineer", label: "Sales Engineer" },
  { value: "marketing_specialist", label: "Marketing Specialist" },
  { value: "content_creator", label: "Content Creator" },
  { value: "blockchain_developer", label: "Blockchain Developer" },
  { value: "ethical_hacker", label: "Ethical Hacker" },
  { value: "data_privacy_officer", label: "Data Privacy Officer" },
  { value: "regulatory_compliance_officer", label: "Regulatory Compliance Officer" },
  { value: "research_scientist", label: "Research Scientist" },
  { value: "innovation_manager", label: "Innovation Manager" },
  { value: "technical_writer", label: "Technical Writer" },
  { value: "system_administrator", label: "System Administrator" },
]


const fullPromptPresets = [
  {
    id: 1,
    title: "SaaS Product Launch",
    role: "product_manager",
    needs: "a landing page",
    tasks: "outline the key features",
    process: "start with a draft, then refine",
    exclusions: "avoid technical jargon",
    format: "HTML",
    example: "Think of Apple's product launch pages",
  },
  {
    id: 2,
    title: "AI Model Deployment",
    role: "ai_engineer",
    needs: "deployment strategy",
    tasks: "identify optimal cloud services",
    process: "evaluate AWS, Google Cloud, and Azure",
    exclusions: "exclude on-premises solutions",
    format: "document",
    example: "Comparison table of cloud services",
  },
  {
    id: 3,
    title: "User Onboarding Flow",
    role: "ui_ux_designer",
    needs: "interactive prototype",
    tasks: "design a step-by-step guide",
    process: "use Figma for prototyping",
    exclusions: "avoid complex sign-up forms",
    format: "Figma link",
    example: "Duolingo's onboarding flow",
  },
  {
    id: 4,
    title: "Data Pipeline Architecture",
    role: "data_engineer",
    needs: "data processing workflow",
    tasks: "design scalable ETL processes",
    process: "draft with Apache Airflow",
    exclusions: "non-cloud solutions",
    format: "diagram",
    example: "Spotify's data architecture",
  },
  {
    id: 5,
    title: "Customer Feedback Analysis",
    role: "data_scientist",
    needs: "sentiment analysis",
    tasks: "analyze customer reviews",
    process: "use NLP techniques",
    exclusions: "manual analysis",
    format: "Jupyter notebook",
    example: "Twitter sentiment analysis",
  },
  {
    id: 6,
    title: "Security Audit Plan",
    role: "cyber_security_specialist",
    needs: "security vulnerabilities report",
    tasks: "perform a comprehensive audit",
    process: "follow OWASP guidelines",
    exclusions: "exclude physical security aspects",
    format: "PDF report",
    example: "ISO 27001 audit report",
  },
  {
    id: 7,
    title: "Scalable Backend Architecture",
    role: "backend_developer",
    needs: "system design document",
    tasks: "design for 100k users",
    process: "consider microservices",
    exclusions: "avoid monolithic architecture",
    format: "Markdown code",
    example: "Uber's backend architecture",
  },
  {
    id: 8,
    title: "Frontend Performance Optimization",
    role: "frontend_developer",
    needs: "page speed improvement plan",
    tasks: "optimize JavaScript and CSS",
    process: "use Google PageSpeed Insights",
    exclusions: "do not remove features",
    format: "document",
    example: "Shopify's performance optimization",
  },
  {
    id: 9,
    title: "DevOps Pipeline Setup",
    role: "devops_engineer",
    needs: "CI/CD pipeline",
    tasks: "automate build and deploy process",
    process: "use Jenkins or GitHub Actions",
    exclusions: "exclude manual deployment steps",
    format: "YAML configuration",
    example: "Docker CI/CD pipeline",
  },
  {
    id: 10,
    title: "Cloud Infrastructure Cost Optimization",
    role: "cloud_architect",
    needs: "cost reduction plan",
    tasks: "analyze and optimize cloud spending",
    process: "use AWS Cost Explorer",
    exclusions: "do not compromise on performance",
    format: "spreadsheet",
    example: "Cloud cost optimization report",
  },
  {
    id: 11,
    title: "Product Roadmap Creation",
    role: "product_manager",
    needs: "visual roadmap",
    tasks: "define milestones and timelines",
    process: "use Trello or Asana for planning",
    exclusions: "avoid vague timelines",
    format: "Trello board link",
    example: "Slack's product roadmap",
  },
  {
    id: 12,
    title: "Market Analysis for New Feature",
    role: "business_analyst",
    needs: "competitive analysis report",
    tasks: "evaluate market demand for a feature",
    process: "conduct surveys and analyze competitors",
    exclusions: "exclude existing features analysis",
    format: "PDF document",
    example: "Feature demand analysis for Zoom's virtual background",
  },
    {
      id: 13,
      title: "Branding and Identity Design",
      role: "graphic_designer",
      needs: "brand book",
      tasks: "create logo, color scheme, and typography",
      process: "start with mood boards",
      exclusions: "avoid copying existing brands",
      format: "PDF",
      example: "Airbnb's brand book",
    },
    {
      id: 14,
      title: "SEO Strategy for SaaS Product",
      role: "seo_specialist",
      needs: "SEO action plan",
      tasks: "keyword research and content creation",
      process: "use SEMrush or Ahrefs for research",
      exclusions: "do not use black-hat SEO techniques",
      format: "document",
      example: "HubSpot's SEO strategy",
    },
    {
      id: 15,
      title: "Mobile App Launch Strategy",
      role: "marketing_manager",
      needs: "launch plan",
      tasks: "plan app store optimization and marketing",
      process: "target both Google Play and App Store",
      exclusions: "exclude paid advertisements",
      format: "presentation",
      example: "TikTok's launch strategy",
    },
    {
      id: 16,
      title: "Investor Pitch Deck",
      role: "founder",
      needs: "pitch deck",
      tasks: "highlight USP, market fit, and financials",
      process: "follow Guy Kawasaki's 10/20/30 rule",
      exclusions: "avoid technical details",
      format: "PowerPoint",
      example: "Airbnb's initial pitch deck",
    },
    {
      id: 17,
      title: "Content Marketing Plan",
      role: "content_manager",
      needs: "editorial calendar",
      tasks: "plan blog posts, ebooks, and webinars",
      process: "use Content Marketing Institute guidelines",
      exclusions: "do not focus on product features",
      format: "spreadsheet",
      example: "Buffer's content marketing strategy",
    },
    {
      id: 18,
      title: "Customer Support Workflow",
      role: "customer_support_manager",
      needs: "support ticket system",
      tasks: "design efficient issue resolution flow",
      process: "implement with Zendesk or Freshdesk",
      exclusions: "exclude phone support",
      format: "flowchart",
      example: "Shopify's support workflow",
    },
    {
      id: 19,
      title: "Email Marketing Campaign",
      role: "digital_marketer",
      needs: "email sequence",
      tasks: "create engaging content for leads",
      process: "use Mailchimp or SendGrid",
      exclusions: "avoid spammy content",
      format: "email templates",
      example: "Dropbox's re-engagement campaign",
    },
    {
      id: 20,
      title: "Legal Compliance Checklist",
      role: "legal_advisor",
      needs: "compliance guide",
      tasks: "ensure product meets legal requirements",
      process: "review GDPR, CCPA, and other relevant laws",
      exclusions: "exclude non-digital compliance",
      format: "checklist",
      example: "Compliance checklist for a fintech startup",
    },
];

const tasksVerbs = [
  'Adapt', 'Analyze', 'Automate', 'Calculate', 'Classify', 'Collaborate', 'Convert',
  'Customize', 'Debug', 'Design', 'Detect', 'Diagnose', 'Discover', 'Enhance',
  'Facilitate', 'Filter', 'Generate', 'Identify', 'Improve', 'Optimize', 'Personalize',
  'Predict', 'Rank', 'Recognise', 'Recommend', 'Simulate', 'Streamline', 'Summarize',
  'Track', 'Translate', 'Validate'
];
const tasksPresets = tasksVerbs.map(verb => ({ label: verb, value: verb }));

const outputVerbs = [ 'plain text', 'well structured format', 'JSON', 'CSV', 'HTML', 'XML', 'Markdown code', 'PDF']
const outputPresets = outputVerbs.map(verb => ({ label: verb, value: verb }));

export {
  rolePresets,
  tasksPresets,
  outputPresets,
  fullPromptPresets
}