
const rolePresets = [
  { value: "ai_engineer", label: "AI Engineer" },
  { value: "machine_learning_engineer", label: "Machine Learning Engineer" },
  { value: "data_scientist", label: "Data Scientist" },
  { value: "data_engineer", label: "Data Engineer" },
  { value: "software_developer", label: "Software Developer" },
  { value: "backend_developer", label: "Backend Developer" },
  { value: "frontend_developer", label: "Frontend Developer" },
  { value: "full_stack_developer", label: "Full Stack Developer" },
  { value: "devops_engineer", label: "DevOps Engineer" },
  { value: "cloud_architect", label: "Cloud Architect" },
  { value: "cyber_security_specialist", label: "Cyber Security Specialist" },
  { value: "ui_ux_designer", label: "UI/UX Designer" },
  { value: "product_manager", label: "Product Manager" },
  { value: "project_manager", label: "Project Manager" },
  { value: "qa_engineer", label: "QA Engineer" },
  { value: "scrum_master", label: "Scrum Master" },
  { value: "business_analyst", label: "Business Analyst" },
  { value: "customer_success_manager", label: "Customer Success Manager" },
  { value: "technical_support_specialist", label: "Technical Support Specialist" },
  { value: "sales_engineer", label: "Sales Engineer" },
  { value: "marketing_specialist", label: "Marketing Specialist" },
  { value: "content_creator", label: "Content Creator" },
  { value: "blockchain_developer", label: "Blockchain Developer" },
  { value: "ethical_hacker", label: "Ethical Hacker" },
  { value: "data_privacy_officer", label: "Data Privacy Officer" },
  { value: "regulatory_compliance_officer", label: "Regulatory Compliance Officer" },
  { value: "research_scientist", label: "Research Scientist" },
  { value: "innovation_manager", label: "Innovation Manager" },
  { value: "technical_writer", label: "Technical Writer" },
  { value: "system_administrator", label: "System Administrator" },
]


const fullPromptPresets = [
  {
    id: 1,
    title: "SaaS Product Launch",
    role: "Frontend Engineer",
    needs: "Create a landing page.",
    tasks: "Structure the layout.",
    process: "Ensure styling, structure, and components are cohesive.",
    exclusions: "Avoid code comments.",
    format: "Output as HTML.",
    example: "See Linear.app for clean copywriting, clear structure, and good UX."
  },
  {
    id: 2,
    title: "AI Model Deployment",
    role: "AI Engineer",
    needs: "Develop a deployment strategy.",
    tasks: "Identify the best cloud services.",
    process: "Compare AWS, Google Cloud, and Azure.",
    exclusions: "Omit on-premises solutions.",
    format: "Present in a document.",
    example: "Create a comparison table of cloud services."
  },
  {
    id: 3,
    title: "User Onboarding Flow",
    role: "UI/UX Designer",
    needs: "Design an interactive prototype for user onboarding.",
    tasks: "Create a step-by-step guide.",
    process: "Utilize Figma for prototyping.",
    exclusions: "Simplify sign-up forms to avoid complexity.",
    format: "Share a Figma link.",
    example: "Refer to Duolingo for an engaging onboarding flow."
  },
  {
    id: 4,
    title: "Data Pipeline Architecture",
    role: "Data Engineer",
    needs: "Design a data processing workflow.",
    tasks: "Create scalable ETL processes.",
    process: "Use Apache Airflow for drafting.",
    exclusions: "Exclude non-cloud solutions.",
    format: "Visualize with a diagram.",
    example: "Look at Spotify's data architecture for inspiration."
  },
  {
    id: 5,
    title: "Customer Feedback Analysis",
    role: "Data Scientist",
    needs: "Conduct sentiment analysis on customer reviews.",
    tasks: "Apply NLP techniques for analysis.",
    process: "Automate the analysis process.",
    exclusions: "Do not perform manual analysis.",
    format: "Compile findings in a Jupyter notebook.",
    example: "Consider Twitter sentiment analysis projects as a reference."
  },
  {
    id: 6,
    title: "Security Audit Plan",
    role: "Cyber Security Specialist",
    needs: "security vulnerabilities report",
    tasks: "perform a comprehensive audit",
    process: "follow OWASP guidelines",
    exclusions: "exclude physical security aspects",
    format: "Plain Text",
    example: "ISO 27001 audit report",
  },
  {
    id: 7,
    title: "Scalable Backend Architecture",
    role: "Backend Developer",
    needs: "System Design Document",
    tasks: "design for 100k users",
    process: "consider microservices",
    exclusions: "avoid monolithic architecture",
    format: "Markdown code",
    example: "Uber's backend architecture",
  },
  {
    id: 8,
    title: "Frontend Performance Optimization",
    role: "Frontend Developer",
    needs: "Page Speed Improvement Plan",
    tasks: "optimize JavaScript and CSS",
    process: "use Google PageSpeed Insights",
    exclusions: "do not remove features",
    format: "Plain Text",
    example: "Shopify's performance optimization",
  },
  {
    id: 9,
    title: "DevOps Pipeline Setup",
    role: "DevOps Engineer",
    needs: "CI/CD pipeline",
    tasks: "automate build and deploy process",
    process: "use Jenkins or GitHub Actions",
    exclusions: "exclude manual deployment steps",
    format: "YAML configuration",
    example: "Docker CI/CD pipeline",
  },
  {
    id: 10,
    title: "Cloud Infrastructure Cost Optimization",
    role: "Cloud Architect",
    needs: "Cost Reduction Plan",
    tasks: "analyze and optimize cloud spending",
    process: "use AWS Cost Explorer",
    exclusions: "do not compromise on performance",
    format: "Markdown Table",
    example: "Cloud cost optimization report",
  },
  {
    id: 11,
    title: "Product Roadmap Creation",
    role: "Product Manager",
    needs: "Roadmap",
    tasks: "define milestones and timelines",
    process: "use bulletpoints and markdown formatting for planning",
    exclusions: "avoid vague timelines",
    format: "Markdown",
    example: "Slack's product roadmap",
  },
  {
    id: 12,
    title: "Market Analysis for New Feature",
    role: "Business Analyst",
    needs: "competitive analysis report",
    tasks: "evaluate market demand for a feature",
    process: "conduct surveys and analyze competitors",
    exclusions: "exclude existing features analysis",
    format: "plain text",
    example: "Feature demand analysis for Zoom's virtual background",
  },
    {
      id: 13,
      title: "Branding and Identity Design",
      role: "Graphic Designer",
      needs: "brand book",
      tasks: "create logo, color scheme, and typography",
      process: "start with mood boards",
      exclusions: "avoid copying existing brands",
      format: "plain text",
      example: "Airbnb's brand book",
    },
    {
      id: 14,
      title: "SEO Strategy for SaaS Product",
      role: "SEO Specialist",
      needs: "SEO action plan",
      tasks: "keyword research and content creation",
      process: "use SEMrush or Ahrefs for research",
      exclusions: "do not use black-hat SEO techniques",
      format: "markdown",
      example: "HubSpot's SEO strategy",
    },
    {
      id: 15,
      title: "Mobile App Launch Strategy",
      role: "marketing manager",
      needs: "launch plan",
      tasks: "plan app store optimization and marketing",
      process: "target both Google Play and App Store",
      exclusions: "exclude paid advertisements",
      format: "presentation",
      example: "TikTok's launch strategy",
    },
    {
      id: 16,
      title: "Investor Pitch Deck",
      role: "Founder",
      needs: "pitch deck",
      tasks: "highlight USP, market fit, and financials",
      process: "follow Guy Kawasaki's 10/20/30 rule",
      exclusions: "avoid technical details",
      format: "markdown",
      example: "Airbnb's initial pitch deck",
    },
    {
      id: 17,
      title: "Content Marketing Plan",
      role: "Content Manager",
      needs: "editorial calendar",
      tasks: "plan blog posts, ebooks, and webinars",
      process: "use Content Marketing Institute guidelines",
      exclusions: "do not focus on product features",
      format: "plain text",
      example: "Buffer's content marketing strategy",
    },
    {
      id: 18,
      title: "Customer Support Workflow",
      role: "customer support manager",
      needs: "support ticket system",
      tasks: "design efficient issue resolution flow",
      process: "implement with Zendesk or Freshdesk",
      exclusions: "exclude phone support",
      format: "flowchart",
      example: "Shopify's support workflow",
    },
    {
      id: 19,
      title: "Email Marketing Campaign",
      role: "digital marketer",
      needs: "email sequence",
      tasks: "create engaging content for leads",
      process: "use Mailchimp or SendGrid",
      exclusions: "avoid spammy content",
      format: "email templates",
      example: "Dropbox's re-engagement campaign",
    },
    {
      id: 20,
      title: "Legal Compliance Checklist",
      role: "legal advisor",
      needs: "compliance guide",
      tasks: "ensure product meets legal requirements",
      process: "review GDPR, CCPA, and other relevant laws",
      exclusions: "exclude non-digital compliance",
      format: "checklist",
      example: "Compliance checklist for a fintech startup",
    },
];

const tasksVerbs = [
  'Adapt', 'Analyze', 'Automate', 'Calculate', 'Classify', 'Collaborate', 'Convert',
  'Customize', 'Debug', 'Design', 'Detect', 'Diagnose', 'Discover', 'Enhance',
  'Facilitate', 'Filter', 'Generate', 'Identify', 'Improve', 'Optimize', 'Personalize',
  'Predict', 'Rank', 'Recognise', 'Recommend', 'Simulate', 'Streamline', 'Summarize',
  'Track', 'Translate', 'Validate'
];
const tasksPresets = tasksVerbs.map(verb => ({ label: verb, value: verb }));

const outputVerbs = [ 'plain text', 'well structured format', 'JSON', 'CSV', 'HTML', 'XML', 'Markdown code', 'PDF']
const outputPresets = outputVerbs.map(verb => ({ label: verb, value: verb }));

export {
  rolePresets,
  tasksPresets,
  outputPresets,
  fullPromptPresets
}